### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by alxmiron** [sealninja/react-i18nify#56]
It would be perfect to add a changelog file. I see a new major v2 version, but can't know anything about breaking changes

**Comment by mastacheata** [comment]
The reason for releasing a new major version was a backwards incompatible change:
2.0.0 replaced momentJS with date-fns


2.0.0-1 switched from using spans in Translate to using fragments
2.0.0-2 added an <I18n> component that I've not yet understood
2.0.0-3 added a render prop to said I18n component (and did some refactoring)
2.0.0-4 Dependency Updates
2.0.0-5 Switched from ISC to MIT License
2.0.0-6 getTranslations function was added
2.0.0-7 Readme updates
2.0.0-8 Date-fns update
2.0.0-9 Dependencies
2.0.0-10 Date-fns update
2.0.0-11 Yet another date-fns update
2.0.0-12, 2.0.0-13  switched the github repo to a new organization
2.0.0-14 documentation
2.0.0-15 license added to readme

2.0.0 release => Use Date-Fns v2 final version instead of beta
2.0.1 release => Regular maintenance update bumping dependencies

**Comment by ivan-kleshnin** [comment]
`date-fns` dependency is huge. 950Kb ungzipped!
Can you consider to cherry-pick only the particular functions you need (if it's possible)?

**Comment by mastacheata** [comment]
Did they really grow that much? Last time I looked they were 10 times smaller than momentJS (which was included before).
Not to say that there's no room for improvement, just wondering why you got there from me going through the commits of the project and writing up what I found.

**Comment by gerbenmeyer** [comment]
Basically it's v2 because of all the breaking changes, but mainly it's a lot simpler, so upgrading should be rather straight forward :smile: 

Also cherry-picked the imports of date-fns now, so hopefully that helps in the size.

**Comment by ivan-kleshnin** [comment]
What are the changes between react-i18nify 2.0 and 3.0?

According to commit thread there shouldn't be much of a difference, 
but I don't have enough time to thoroughly verify that. 

Pls. tell me (us) if there're something API-related we should be concerned about.

**Comment by gerbenmeyer** [comment]
The only change is that only the `eu-US` locale of `date-fns` is included by default, so if you want to use date localization of other languages, they have to be added with `addLocale` or `addLocales`.

**Comment by ivan-kleshnin** [comment]
Great, thanks!
