### ISSUE TITLE
Translation with html tag and replacement

### ISSUE THREAD

**Issue by 3dw1np** [sealninja/react-i18nify#62]
With the drop of dangerousHTML prop in the new version of react-i18nify. 
If I combine html tag and replacement in the same translation, it doesn't work (it was working with v1). 

```
export default {
   label_phone: <div>Phone: <strong>%{phone_number}</strong></div>
}

<Translate
   value="label_phone"
   phone_number="+99999999999"
/>
```

**Comment by gerbenmeyer** [comment]
The main reason it's dropped is because `dangerouslySetInnerHTML` is something to be avoided.
Better would be to do something like `<div><Translate value="phone" />: <strong>{phone_number}</strong></div>`.
If you really want to stick with dangerous html, you could do this: `<div dangerouslySetInnerHTML={{ __html: t('label_phone;}} />`.
